### ISSUE TITLE
Can you use Mira to view a user profile?

### ISSUE THREAD

**Issue by WadeLewis** [thecsw/mira#1]
For example, if I wanted to automatically stream new comments made by my account to a file on local disc, is there a way to "stream" those comments, similar to how the subreddit listener serves new posts?

**Comment by thecsw** [comment]
@WadeLewis Thanks for the issue! That’s a great question. Mira has a `reddit.GetUser()` method that will return general user information. Streaming one’s comments is a great idea and expect it in the next release!

**Comment by thecsw** [comment]
@WadeLewis release v2.0.0 has new redditor profile options! You can stream one's comments the same way you would stream comments of a subreddit. Here is a quick example:

``` go
// Errors are ignored for brevity
package main

import (
	"fmt"

	"github.com/thecsw/mira"
)

func main() {
	r, _ := mira.Init(mira.ReadCredsFromFile("login.conf"))
	c, _, _ := r.Redditor("thecsw").StreamComments()
	for {
		msg := <-c
		fmt.Println(msg.GetTitle())
	}
}
```

**Comment by thecsw** [comment]
Closing for now. Feel free to reopen if further inquiry is needed.
