### ISSUE TITLE
Can you go to the next page?

### ISSUE THREAD

**Issue by emmggi** [thecsw/mira#5]
Hi
I can't figure out how to go to the next page, it only prints the first one. I also tried without separating the id from the identifier (eg. d7gsv instead of t3_d7gsv). I would also like to know if there's a way to sort these by newest. I only saw Submissions() having a sort argument not SubmissionsAfter(). This is my code

```golang
var lastPostId string

// Initialize a new mira instance
r, err := mira.Init(creds)
if err != nil {
	log.Fatal(err)
}	

if rippingType == "r" {
	postCount := 1
	for {
		subsAfter, err := r.Subreddit(rippingIdentifier).SubmissionsAfter(lastPostId, 100)
		if err != nil {
			log.Printf("Failed to fetch /%s/%s: %v\n", rippingType, rippingIdentifier, err)
		}

		// Define an output folder and print out a message
		rippingIdentifier = subsAfter[0].GetSubreddit()
		if !isOutputUserDefined {
			outputFolder = "rips/reddit_sub_" + rippingIdentifier + "/"
		}
		colorstring.Printf("[green]Ripping /%s/%s // Output folder: %s\n", rippingType, rippingIdentifier, outputFolder)

		// Iterate over each page
		for _, v := range subsAfter {
			fmt.Printf("[%d] [/%s/%s] %s // Downloading: %s\n", postCount, rippingType, rippingIdentifier, v.GetId(), v.GetUrl())
			lastPostId = strings.Split(v.GetId(), "_")[1]
			postCount ++
		}
	}		
}
```

**Comment by thecsw** [comment]
Hey, @electronicous!

Alright, first thing is that `mira` always requires an identifier, like `t3_`, etc. Because mira is making a direct payload to reddit. It can be improved as if mira would check for the identifier and add it if missing.

`SubmissionsAfter(...)` automatically goes through `new` sorting:
``` golang
func (c *Reddit) getSubredditPostsAfter(sr string, last string, limit int) ([]models.PostListingChild, error) {
	target := RedditOauth + "/r/" + sr + "/new.json"
	...
```
`SubmissionsAfter(...)` was created for streaming purposes, never thought someone would need to use it exposed. Mira's primary concern was to provide robust and a very simple way to stream data from reddit. I never thought of implementing a nice paging system. I guess that kinda answers your question.

There is a solution to your problem. I can use this issue to implement a paging system for mira or you can make your own mira call and page the results (you can also make a PR if you want). 

`MiraRequest()` is an exported method for `*Reddit` that can allow you to access any reddit endpoint and implement all calls you need.

``` golang
func (c *Reddit) MiraRequest(method string, target string, payload map[string]string) ([]byte, error) {...}
```

Let me know if you have any questions

**Comment by emmggi** [comment]
Thank you for your response. I'm not sure if I'm doing this right, since I'm getting empty responses like this. 
```
{  false false false  false     []  0  0 false 0  0  false false false   0 false    false   false    false false false  false false 0  false  false false false  false   false  false false   false false false false false      false  false false    false  false    0 []  false}
```
`rippingType` is either `r` or `u` and `rippingIdentifier` is the name of the subreddit or user. My code:
```go
var unmarshaled models.SubredditData
var lastRedditPostID string

// Initialize a new authenticated mira instance
r, err := mira.Init(creds)
if err != nil {
	log.Fatal("Failed initializing mira:", err)
}

// Start scraping
newRequest, err := r.MiraRequest("GET", fmt.Sprintf("https://oauth.reddit.com/%s/%s", rippingType, rippingIdentifier), map[string]string{
	"sort": "new",
	"count": "50",
	"after": lastRedditPostID,
	"api_type": "json",
	"show": "all",
})
if err != nil {
	log.Fatalf("Failed to fetch /%s/%s: %v\n", rippingType, rippingIdentifier, err)
}

err = json.Unmarshal(newRequest, &unmarshaled)
if err != nil {
	log.Fatalln("Failed unmarshaling to struct:", err)
}

fmt.Println(unmarshaled)
```
also tried
```go
newRequest, err := r.MiraRequest("GET", "https://oauth.reddit.com/", map[string]string{
	"thing_id": fmt.Sprintf("%s/%s", rippingType, rippingIdentifier),
	"after": lastRedditPostID,
	"sort": "new",
	})
```

creds is a `*mira.Credentials` from a struct
```
creds := mira.Credentials{
	ClientId:     c.Reddit.App.ClientID,
	ClientSecret: c.Reddit.App.ClientSecret,
	Username:     c.Reddit.App.Username,
	Password:     c.Reddit.App.Password,
	UserAgent:    c.Reddit.BotAgent,
}
```

**Comment by thecsw** [comment]
@electronicous your `unmarshalled` will depend on your ripping type. golang doesn't really have generics, so we have to diy the whole thing through a bunch of hard-coded structs. If it's a subreddit or a submission, you will have to somehow take that into account

**Comment by emmggi** [comment]
I see. I thought I can use one of those in the docs. Sorry. I think I can manage it now.

**Comment by thecsw** [comment]
@electronicous let me know if you have any questions
