### ISSUE TITLE
Streaming without login

### ISSUE THREAD

**Issue by DarkWingMcQuack** [thecsw/mira#6]
Is there a possibility to stream submissions without login credentials? Since I dont want to post and only want to stream submissions of a subreddit, which should be doable via the public API this should be doable without login credentials

**Comment by thecsw** [comment]
Good point! I think it should be enough to just swap the main reddit oauth endpoint to something else. I will probably add the endpoint target to `Reddit` struct so anyone can modify it. Thanks!
